version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  stock-system:
    build:
      context: ./stock-system
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "12345:12345"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=passw0rd
      - DB_NAME=postgres
    entrypoint: ["/usr/local/bin/wait-for-db.sh", "db", "5432", "--"]
    command: ["./service"] 

volumes:
  postgres-data:
