version: '2'

services:
  stock_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: passw0rd
    volumes:
      - ./init_sql:/docker-entrypoint-initdb.d
    expose:
      - "5432"
    ports:
      - "54321:5432"

  server:
    build: ./stock-system
    command: ./service
    volumes:
      - ./stock-system:/code
    expose:
      - "12345"
    ports:
      - "12345:12345"
    depends_on:
      - stock_db
